services:
  go-http:
    build:
      context: go-http
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ADDR=:8000
      - GOMAXPROCS=1
      - CHAOS_ENDPOINT=http://rust-axum:3000/chaos-server/
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G
  js-adonisjs:
    build:
      context: js-adonisjs
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - HOST=0.0.0.0
      - PORT=3333
      - APP_KEY="qdhEGKJ4kn2HiS8o1S5Vd5H66Cp_pkLm"
      - CHAOS_ENDPOINT=http://rust-axum:3000/chaos-server/
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G

  rust-axum:
    build:
      context: rust-axum
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ADDR=:3000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G
